services:
  - type: web
    name: core
    runtime: docker
    dockerContext: "."
    dockerfilePath: Dockerfile
    preDeployCommand: python manage.py migrate
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
