# Generated by Django 3.1.7 on 2021-02-27 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('level', models.IntegerField(choices=[(1, 'Introductorio'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Completo')], default=1)),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('users', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
            ],
        ),
    ]
